const content = [
	{
		id: 1,
		xp: `Clive Alliance`,
		period: `December 2023 - Present (Contract)`,
		title: `Frontend Developer`,
		shalaye1: `Responsible for implementing web-based applications, ensuring seamless functionality and user experience.`,
		shalaye2: `Collaborate closely with the lead engineer, actively seeking feedback and incorporating best practices into development.`,
		shalaye3: `Ensure all implementations align with product requirements and follow industry-standard practices.`,
		shalaye4: `Participate in meetings and product testing exercises to continuously refine the product.`,
	},
	{
		id: 2,
		xp: `Edustipend`,
		period: `June 2023 - Present (Contract)`,
		title: `Frontend Developer`,
		shalaye1: `Build UI components and features using React, ensuring they meet both design and product specifications.`,
		shalaye2: `Work closely with technical leadership, product designers, product managers, and the backend team to ensure smooth collaboration.`,
		shalaye3: `Contribute to the development and maintenance of the component library system using Storybook.`,
		shalaye4: `Write and maintain unit tests to ensure code quality, adhering to the team's defined software development processes.`,
		shalaye5: `Participate in daily standups and other required team meetings to stay aligned with the project's progress.`,
	},
	{
		id: 3,
		xp: `Robs Hub`,
		period: `March 2022 - March 2023`,
		title: `Frontend Tutor`,
		shalaye1: `Maintain the office space and ensure smooth daily operations.`,
		shalaye2: `Tutor students on the fundamentals of web development, focusing on frontend technologies.`,
		shalaye3: `Coordinate with other staff members to support students and ensure efficient workflow.`,
	},
	{
		id: 4,
		xp: `Zuri Training`,
		period: `April 2022 - July 2022`,
		title: `Frontend Trainee`,
		shalaye1: `Worked as part of a team of developers and designers, contributing as a frontend developer using HTML, CSS, and JavaScript.`,
		shalaye2: `Completed tasks on time while collaborating with other trainees to meet deadlines and ensure project success.`,
		shalaye3: `Attended classes and received mentorship to improve my frontend development skills.`,
		shalaye4: `Collaborated with fellow developers for the first time, overcoming initial challenges to deliver a cohesive final project.`,
		shalaye5: `Contributed to the final project as a frontend developer, gaining valuable teamwork experience in a real-world environment.`,
	},
	{
		id: 5,
		xp: `HNG 9 Finalist`,
		period: `September 2022 - January 2023`,
		title: `Frontend Intern`,
		shalaye1: `Started as an independent frontend developer intern, using React to complete assigned tasks.`,
		shalaye2: `Collaborated in a cross-functional team with designers, marketers, project managers, and other developers to implement designs and user flows.`,
		shalaye3: `Worked alongside other developers to bring designs and user flows to life, ensuring alignment with project goals and timelines.`,
	},
];

export default content;
